# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newEkran.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        Form.setMinimumSize(QtCore.QSize(1000, 700))
        Form.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/NewLogoIET-100.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.bgLabel = QtWidgets.QLabel(Form)
        self.bgLabel.setGeometry(QtCore.QRect(0, -10, 1011, 771))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bgLabel.setFont(font)
        self.bgLabel.setStyleSheet("background-color:rgb(75,75,75);")
        self.bgLabel.setText("")
        self.bgLabel.setObjectName("bgLabel")
        self.bgLAbel2 = QtWidgets.QLabel(Form)
        self.bgLAbel2.setGeometry(QtCore.QRect(660, 0, 341, 701))
        self.bgLAbel2.setStyleSheet("background-color:rgba(56, 184, 141,255)")
        self.bgLAbel2.setText("")
        self.bgLAbel2.setObjectName("bgLAbel2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(690, 500, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.qrTaraButton = QtWidgets.QPushButton(Form)
        self.qrTaraButton.setGeometry(QtCore.QRect(590, 600, 51, 51))
        self.qrTaraButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.qrTaraButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/TARALOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qrTaraButton.setIcon(icon1)
        self.qrTaraButton.setIconSize(QtCore.QSize(48, 48))
        self.qrTaraButton.setObjectName("qrTaraButton")
        self.silButton = QtWidgets.QPushButton(Form)
        self.silButton.setGeometry(QtCore.QRect(940, 600, 31, 41))
        self.silButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.silButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/copkutusulogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.silButton.setIcon(icon2)
        self.silButton.setIconSize(QtCore.QSize(32, 32))
        self.silButton.setObjectName("silButton")
        self.mailButton = QtWidgets.QPushButton(Form)
        self.mailButton.setGeometry(QtCore.QRect(920, 510, 41, 41))
        self.mailButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.mailButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/maillogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailButton.setIcon(icon3)
        self.mailButton.setIconSize(QtCore.QSize(32, 32))
        self.mailButton.setObjectName("mailButton")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(790, 670, 91, 21))
        self.pushButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/caftelleblacktexttt@4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.bilgilabel2 = QtWidgets.QLabel(Form)
        self.bilgilabel2.setGeometry(QtCore.QRect(40, 30, 571, 541))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bilgilabel2.setFont(font)
        self.bilgilabel2.setStyleSheet("color:white")
        self.bilgilabel2.setText("")
        self.bilgilabel2.setObjectName("bilgilabel2")
        self.silgiLabel = QtWidgets.QLabel(Form)
        self.silgiLabel.setGeometry(QtCore.QRect(680, 590, 251, 51))
        self.silgiLabel.setStyleSheet("color:white;")
        self.silgiLabel.setObjectName("silgiLabel")
        self.mailLabel = QtWidgets.QLabel(Form)
        self.mailLabel.setGeometry(QtCore.QRect(700, 470, 201, 31))
        self.mailLabel.setStyleSheet("color:white;")
        self.mailLabel.setObjectName("mailLabel")
        self.durumLabel = QtWidgets.QLabel(Form)
        self.durumLabel.setGeometry(QtCore.QRect(680, 50, 301, 131))
        self.durumLabel.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;""\n"
"\n"
"")
        self.durumLabel.setText("")
        self.durumLabel.setObjectName("durumLabel")
        self.hizmetLabel = QtWidgets.QLabel(Form)
        self.hizmetLabel.setGeometry(QtCore.QRect(690, 280, 290, 50))
        self.hizmetLabel.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;""\n"
"\n"
"")
        self.hizmetLabel.setObjectName("hizmetLabel")
        self.isemritrLAbel = QtWidgets.QLabel(Form)
        self.isemritrLAbel.setGeometry(QtCore.QRect(690, 400, 290, 50))
        self.isemritrLAbel.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;""\n"
"\n"
"")
        self.isemritrLAbel.setObjectName("isemritrLAbel")
        self.isemrinumLabel = QtWidgets.QLabel(Form)
        self.isemrinumLabel.setGeometry(QtCore.QRect(690, 340, 290, 50))
        self.isemrinumLabel.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;""\n"
"\n"
"")
        self.isemrinumLabel.setObjectName("isemrinumLabel")
        self.musteriLabel = QtWidgets.QLabel(Form)
        self.musteriLabel.setGeometry(QtCore.QRect(690, 220, 290, 50))
        self.musteriLabel.setStyleSheet("background-color:rgb(65, 195, 150);\n"
"border:none;\n"
"border-radius:20px;\n"
"padding:10px;\n"
"color:white;""\n"
"\n"
"")
        self.musteriLabel.setObjectName("musteriLabel")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(780, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.silgiLabel.setText(_translate("Form", "Taranan verileri mail ile gönderdikten sonra\n"
" silmek bir sonraki taramayı daha güvenli hale getirir."))
        self.mailLabel.setText(_translate("Form", "Mail adresinizi ya da kullanıcı adınızı yazınız"))
        self.hizmetLabel.setText(_translate("Form", "Hizmet Nuamarsı:"))
        self.isemritrLAbel.setText(_translate("Form", "İş Emri Türü:"))
        self.isemrinumLabel.setText(_translate("Form", "İş Emri Numarası:"))
        self.musteriLabel.setText(_translate("Form", "Müşteri Numarası:"))
        self.label.setText(_translate("Form", "Bilgi Penceresi"))
from image import taramalogo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
